package eu.bbmri.eric.csit.service.negotiator.database.model;

public enum NegotiationResourceState {
    SUBMITTED,
    REPRESENTATIVE_CONTACTED,
    REPRESENTATIVE_UNREACHABLE,
    RETURNED_FOR_RESUBMISSION,
    CHECKING_AVAILABILITY,
    RESOURCE_AVAILABLE,
    RESOURCE_UNAVAILABLE,
    ACCESS_CONDITIONS_INDICATED,
    ACCESS_CONDITIONS_MET,
    RESOURCE_MADE_AVAILABLE,

}
