swagger: '2.0'
info:
  description: 'BBMRI-ERIC Negotiator Service API. The Service is running at [https://negotiator.bbmri-eric.eu](https://negotiator.bbmri-eric.eu)'
  version: 2.0.0
  title: BBMRI-ERIC Negotiator
  termsOfService: 'https://web.bbmri-eric.eu/Policies/BBMRI-ERIC-AUP-IT-Services-1_0.pdf'
  contact:
    email: negotiator@helpdesk.bbmri-eric.eu
  license:
    name: The GNU General Public License v3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
host: negotiator.bbmri-eric.eu
basePath: /api
schemes:
  - https
tags:
  - name: status
    description: Get version and statistics of the called Negotiator instance.
  - name: directory
    description: 'Calls used by registered findability services (such as BBMRI-ERIC Directory, GBA/BBMRI-ERIC Locator, RD-Connect Finder) to create new requests or modify existing requests.'
  - name: list
    description: List of biobanks and collections from all the findability services registered in the Negotiator.
  - name: perun
    description: Calls used by Authentication and Authorization Infrastructure (BBMRI-ERIC AAI) to update authentication and authorization information in the Negotiator.
  - name: request
    description: Import export of requests
paths:
  /status:
    get:
      tags:
        - status
      summary: Get version and statistics of the called Negotiator instance.
      description: 'Listes depoyed version of the BBMRI-ERIC Negotiator service, basic statistic of the service.'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Status'
        '400':
          description: Invalid status value
  /directory/create_query:
    post:
      tags:
        - directory
      summary: Creates a new query.
      description: 'Takes a JSON query object with information of the search criteria and results of the directory. Stores it temporary in the database and returns a redirect URL for the directory. With this URL the directory can redirect the user to the query edit page. I case of updating a existing query or extending an exiting request, a token is provided for identification.'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            $ref: '#/definitions/Query'
      responses:
        '201':
          description: successful created
          schema:
            $ref: '#/definitions/QueryCreateResponse'
  /v2/list:
    get:
      tags:
        - list
      summary: List of Biobanks and Collections in all directories
      description: Returns a JSON array with a hierarchical structure of all directories integrated into the \Negotiator. For each directory all biobanks registered are listed with the identifying ID of the directory. In the biobank a list of all associated collections is listed.
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/List'
  /perun/users:
    post:
      tags:
        - perun
      summary: Update AAI user information
      description: Update AAI user information from biobanks and collections
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            $ref: '#/definitions/AAIUser'
      responses:
        '200':
          description: successful operation
  /perun/networks/users:
    post:
      tags:
        - perun
      summary: Update AAI user information for network users
      description: Update AAI user information from networks
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            $ref: '#/definitions/AAIUserMapping'
      responses:
        '200':
          description: successful operation
  /perun/mapping:
    post:
      tags:
        - perun
      summary: Update AAI user collection mapping
      description: Update AAI user collections mapping
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            $ref: '#/definitions/AAIUser'
      responses:
        '200':
          description: successful operation
  /perun/networks/mapping:
    post:
      tags:
        - perun
      summary: Update AAI user network mapping
      description: Update AAI user network mapping
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            $ref: '#/definitions/AAIUser'
      responses:
        '200':
          description: successful operation
  /v2/io/export:
    get:
      tags:
        - request
      summary: Get request details by requestId
      description: Get detailed data for a request by requestId
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            type: object
            properties:
              requestId:
                type: integer
                format: int64
                example: 131
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Request'
  /v2/io/import:
    post:
      tags:
        - request
      summary: Import a request to negotiator
      description: Import a request to negotiator
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Query parameters
          required: true
          schema:
            $ref: '#/definitions/Request'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              requestId:
                type: integer
                format: int64
                example: 131
              requestURL:
                type: string
definitions:
  Status:
    type: object
    properties:
      biobanks:
        type: integer
        format: int64
        example: 1791
        description: number of registered biobanks in the Negotiator instance
      attachments:
        type: integer
        format: int64
        example: 111
        description: number of attachments uploaded into the system
      collections:
        type: integer
        format: int64
        example: 4515
        description: number of registered collections in the Negotiator instance
      queries_with_matches:
        type: integer
        format: int64
        example: 271
        description: number of queries with at least one matching collection
      build_time:
        type: string
        pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$'
        example: '2020-09-10 11:25'
        description: date/time when current Negotiator version was built
      used:
        type: integer
        format: int64
        example: 49476
        description: used diskspace on the system
      free:
        type: integer
        format: int64
        example: 49173
        description: free diskspace on the system
      queries:
        type: integer
        format: int64
        example: 285
        description: total number of queries registered in the Negotiator instance
      version:
        type: string
        example: 2.1.2-SNAPSHOT
        description: version of the Negotiator instance
      users:
        type: integer
        format: int64
        example: 364
        description: number of users registered  in the Negotiator instance
  Query:
    type: object
    properties:
      URL:
        type: string
      humanReadable:
        type: string
      collections:
        type: array
        items:
          type: object
          properties:
            biobankId:
              type: string
            collectionId:
              type: string
  QueryCreateResponse:
    type: object
    properties:
      redirect_uri:
        type: string
  List:
    type: array
    items:
      type: object
      properties:
        directory:
          type: object
          properties:
            name:
              type: string
            url:
              type: string
            description:
              type: string
            Biobanks:
              type: array
              items:
                type: object
                properties:
                  directory_id:
                    type: string
                  name:
                    type: string
                  collections:
                    type: array
                    items:
                      type: object
                      properties:
                        directory_id:
                          type: string
                        name:
                          type: string
  AAIUser:
    type: array
    items:
      type: object
      properties:
        organization:
          type: string
        id:
          type: integer
          format: int64
        displayName:
          type: string
        status:
          type: string
        mail:
          type: string
        identities:
          type: array
          items:
            type: string
  AAIUserMapping:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        directory:
          type: string
        id:
          type: string
        members:
          type: array
          items:
            type: object
            properties:
              userId:
                type: string
  Request:
    type: object
    properties:
      requestId:
        type: integer
        format: int64
      title:
        type: string
      projectDescription:
        type: string
      requestDescription:
        type: string
      ethicsVote:
        type: string
      testRequest:
        type: boolean
      creationTime:
        type: string
        pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$'
        example: '2020-09-10 11:25'
        description: date/time when request was created
      collections:
        type: array
        description: array of collection involved in the request (optional)
        items:
          type: object
          properties:
            biobankId:
              type: string
            collectionId:
              type: string
      query:
        type: array
        items:
          type: object
          description: array of queries for the request (optional)
          properties:
            queryParameters:
              type: string
            humanReadable:
              type: string
              example: selected countries are AT
              description: human readable version of the query
            url:
              type: string
              description: redirect url to the directory
            numberOfCollections:
              type: integer
              format: int64
      