services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - '--config.file=/etc/prometheus/prometheus.yml'

