server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/negotiator
    username: negotiator
    password: negotiator
    initialize: true
  sql:
    init:
      mode: never
      platform: postgres
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: "yyyy-MM-dd"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

