server:
  port: 8081
  servlet:
    context-path: "/api"
management:
  endpoint:
    health:
      enabled: true
      show-components: always
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
spring:
  mail:
    host: "localhost"
    port: 1025
    username: "user"
    password: "pass"
  application:
    name: "Negotiator"
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ""
          client-secret: ""
          introspection-uri: ""
        jwt:
          user-info-uri: ""
          issuer-uri: ""
          jwks-url: ""
          audiences: negotiator-api
negotiator:
  molgenis-url: ""
  frontend-url: ""
  authorization:
    claim: ""
    admin-claim-value: ""
    researcher-claim-value: ""
    biobanker-claim-value: ""
    subject-claim: ""
    resource-claim-prefix: ""
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: info
springdoc:
  show-actuator: true
