spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/negotiator
    username: negotiator
    password: negotiator
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  jackson:
    date-format: "yyyy-MM-dd"
  flyway:
    enabled: true
    user:
    password:
    schemas:
    url:
    baseline-on-migrate: true
    locations: classpath:db/migration/{vendor},filesystem:/app/data
notification:
  cron-schedule-expression: "0 0 * * * *"
logging:
  file:
    name: "/var/log/negotiator/negotiator.log"
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    org.springframeworf.web: info
    org.springframework.security: info
    eu.bbmri_eric.negotiator: info
reminder:
  trigger-duration-days: "P7D"
  cron-schedule-expression: "0 0 8 * * MON"