spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/negotiator
    username: negotiator
    password: negotiator
    database: negotiator
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    date-format: "yyyy-MM-dd"
  flyway:
    locations: classpath:db/migration/,filesystem:/app/data
notification:
  cron-schedule-expression: "0 0 * * * *"
logging:
  file:
    name: "/var/log/negotiator/negotiator.log"
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    org.springframeworf.web: info
    org.springframework.security: info
    eu.bbmri_eric.negotiator: info
reminder:
  trigger-duration-days: "P7D"
  cron-schedule-expression: "0 0 0 * * TUE"