spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:negotiator;INIT=RUNSCRIPT FROM 'classpath:dev/init.sql'
    username: negotiator
    password: negotiator
    initialize: true
  sql:
    init:
      mode: always
      platform: test
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://login.bbmri-eric.eu/oidc/"
          type: "JWT"
negotiator:
  frontend-url: "http://localhost"
  authorization:
    claim: "authz"
    admin-claim-value: "admin_group"
    researcher-claim-value: "researcher_group"
    biobanker-claim-value: "biobanker_group"
    subject-claim: "subject_id"
    resource-claim-prefix: "resource_id"
