spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:negotiator;MODE=PostgreSQL;INIT=RUNSCRIPT FROM 'classpath:dev/init.sql'
    username: negotiator
    password: negotiator
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: always
      platform: h2
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    date-format: "yyyy-MM-dd"
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: "http://localhost:4011/connect/userinfo"
          issuer-uri: "http://localhost:4011"
          jwk-set-uri: "http://localhost:4011/.well-known/openid-configuration/jwks"
          type: "JWT"
          audiences: negotiator-api
        opaquetoken:
          client-id: "negotiator-api"
          client-secret: "negotiator-secret"
          introspection-uri: "http://localhost:4011/connect/introspect"
negotiator:
  molgenis-url: "https://bbmritestnn.gcc.rug.nl"
  frontend-url: "http://localhost:8080"
  authorization:
    claim: "eduperson_entitlement"
    admin-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:admins#perun.bbmri-eric.eu"
    researcher-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu"
    biobanker-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory#perun.bbmri-eric.eu"
    subject-claim: "sub"
    resource-claim-prefix: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:"
logging:
  level:
    org:
      springframework:
        security: debug
        jdbc:
          datasource:
            init:
              ScriptUtils: debug


