spring:
  mail:
    host: "localhost"
    port: 1025
    username: "user"
    password: "pass"
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgres:///negotiator
    username: negotiator
    password: negotiator
    database: negotiator
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: negotiator
    password: negotiator
    url: jdbc:tc:postgresql:///negotiator
    locations: classpath:db/migration/,db/dev/migration
  jackson:
    date-format: "yyyy-MM-dd"
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: "http://localhost:4011/connect/userinfo"
          issuer-uri: "http://localhost:4011"
          jwk-set-uri: "http://localhost:4011/.well-known/openid-configuration/jwks"
          type: "JWT"
          audiences: https://negotiator.bbmri-eric.eu
        opaquetoken:
          client-id: "https%3A//negotiator.bbmri-eric.eu"
          client-secret: "negotiator-secret"
          introspection-uri: "http://localhost:4011/connect/introspect"
springdoc:
  oAuthFlow:
    authorizationUrl: "http://localhost:4011/connect/authorize"
    tokenUrl: "http://localhost:4011/connect/token"
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: "client-credentials-mock-client"
      client-secret: "authorization-code-with-pkce-client-secret"
      scopes: "openid profile email permissions some-app-scope-1"
negotiator:
  molgenis-url: "https://bbmritestnn.gcc.rug.nl"
  frontend-url: "http://localhost:8080"
  authorization:
    claim: "eduperson_entitlement"
    admin-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:admins#perun.bbmri-eric.eu"
    researcher-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu"
    biobanker-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory#perun.bbmri-eric.eu"
    subject-claim: "sub"
    resource-claim-prefix: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:"
notification:
  cron-schedule-expression: "0 * * * * *"
logging:
  level:
    org:
      springframework:
        security: debug
        jdbc:
          datasource:
            init:
              ScriptUtils: debug
    org.springframeworf.web: debug
    eu.bbmri_eric.negotiator: debug
reminder:
  trigger-duration-days: "PT2M"
  cron-schedule-expression: "0 */5 * ? * *"