spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:negotiator;MODE=PostgreSQL;INIT=RUNSCRIPT FROM 'classpath:db/test/add_json_extract_function.sql'"
    username: negotiator
    password: negotiator
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  sql:
    init:
      mode: always
      platform: test
      data-locations: classpath:db/test/migration/R__Initial_data.sql
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://testoidc"
          type: "JWT"
  flyway:
    enabled: false
negotiator:
  molgenis-url: "http://localhost:8088/directory"
  frontend-url: "http://localhost"
  authorization:
    claim: "authz"
    admin-claim-value: "admin_group"
    researcher-claim-value: "researcher_group"
    biobanker-claim-value: "biobanker_group"
    subject-claim: "subject_id"
    resource-claim-prefix: "resource_id"
reminder:
  trigger-duration-days: "PT0S"
