spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/negotiator
    username: negotiator
    password: negotiator
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: true
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: "yyyy-MM-dd"
