spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgres:///negotiator
    username: negotiator
    password: negotiator
    database: negotiator
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: negotiator
    password: negotiator
    url: jdbc:tc:postgresql:///negotiator
    locations: classpath:db/migration/{vendor},db/dev/migration
  jackson:
    date-format: "yyyy-MM-dd"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://testoidc"
          type: "JWT"
negotiator:
  molgenis-url: "http://localhost:8088/directory"
  frontend-url: "http://localhost"
  authorization:
    claim: "authz"
    admin-claim-value: "admin_group"
    researcher-claim-value: "researcher_group"
    biobanker-claim-value: "biobanker_group"
    subject-claim: "subject_id"
    resource-claim-prefix: "resource_id"
