server:
  port: 8081
  servlet:
    context-path: "/api"
spring:
  application:
    name: "Negotiator"
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: ""
          issuer-uri: ""
negotiator:
  frontend-url: ""
  authorization:
    claim: ""
    admin-claim-value: ""
    researcher-claim-value: ""
    biobanker-claim-value: ""
    subject-claim: ""
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

