
server:
  port: 8081
  servlet:
    context-path: "/api"
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-components: always
  info:
    env:
      enabled: true
    build:
      enabled: true
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
spring:
  mail:
    host: "localhost"
    port: 1025
    username: "user"
    password: "pass"
  application:
    name: "Negotiator"
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    user:
    password:
    url:
    locations:
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: false
      max-age: 3600
    csrf:
      enabled: false
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ""
          client-secret: ""
          introspection-uri: ""
        jwt:
          user-info-uri: ""
          issuer-uri: ""
          jwks-url: ""
          audiences: negotiator-api
  profiles:
    default: prod
  springdoc:
    oAuthFlow:
      authorizationUrl: ""
      tokenUrl: ""
    swagger-ui:
      oauth:
        use-pkce-with-authorization-code-grant: true
        client-id: ""
        client-secret: ""
        scopes: ""
negotiator:
  molgenis-url: ""
  frontend-url: ""
  authorization:
    claim: ""
    admin-claim-value: ""
    researcher-claim-value: ""
    biobanker-claim-value: ""
    subject-claim: ""
    resource-claim-prefix: ""
notification:
  cron-schedule-expression: "0 0 * * * *"
logging:
  level:
    root: info
springdoc:
  show-actuator: true
info:
  application:
    name: "BBMRI-ERIC Negotiator"
    description: "An Open-source access negotiation system for Research Infrastructures."
    environment: "Production"
    license:
      name: "GNU Affero General Public License v3.0"
      url: "https://www.gnu.org/licenses/agpl-3.0.en.html#license-text"
