server:
  port: 8080
  servlet:
    context-path: "/api"
spring:
  application:
    name: "Negotiator"
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
negotiator:
  redirectPath: "/gui/request"

  authorization:
    claim: ""
    adminClaimValue: ""
    researcherClaimValue: ""
    biobankerClaimValue: ""
    subjectClaim: ""
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

