spring:
  flyway:
    clean-disabled: false
    locations: classpath:db/migration/, classpath:db/test/migration
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://testoidc"
          type: "JWT"
negotiator:
  molgenis-url: "http://localhost:8088/directory"
  frontend-url: "http://localhost"
  authorization:
    claim: "authz"
    admin-claim-value: "admin_group"
    researcher-claim-value: "researcher_group"
    biobanker-claim-value: "biobanker_group"
    subject-claim: "subject_id"
    resource-claim-prefix: "resource_id"
reminder:
  trigger-duration-days: "PT0S"