spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:negotiator;INIT=RUNSCRIPT FROM 'classpath:dev/init.sql'
    username: negotiator
    password: negotiator
    initialize: true
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    date-format: "yyyy-MM-dd"
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: "http://localhost:4011/connect/userinfo"
          issuer-uri: "http://localhost:4011"
          jwk-set-uri: "http://localhost:4011/.well-known/openid-configuration/jwks"
          type: "JWT"
negotiator:
  frontend-url: "http://localhost:8080"
  authorization:
    claim: "eduperson_entitlement"
    admin-claim-value: ""
    researcher-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu"
    biobanker-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:biobankers#perun.bbmri-eric.eu"
    subject-claim: "preferred_username"
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug


