spring:
  mail:
    host: "localhost"
    port: 1025
    username: "user"
    password: "pass"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:negotiator;MODE=PostgreSQL
    username: negotiator
    password: negotiator
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: never
      platform: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    user: negotiator
    password: negotiator
    url: jdbc:h2:mem:negotiator;MODE=PostgreSQL
    locations: classpath:db/migration/{vendor},db/dev/migration
  jackson:
    date-format: "yyyy-MM-dd"
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: "http://localhost:4011/connect/userinfo"
          issuer-uri: "http://localhost:4011"
          jwk-set-uri: "http://localhost:4011/.well-known/openid-configuration/jwks"
          type: "JWT"
          audiences: https://negotiator.bbmri-eric.eu
        opaquetoken:
          client-id: "https%3A//negotiator.bbmri-eric.eu"
          client-secret: "negotiator-secret"
          introspection-uri: "http://localhost:4011/connect/introspect"
negotiator:
  molgenis-url: "https://bbmritestnn.gcc.rug.nl"
  frontend-url: "http://localhost:8080"
  authorization:
    claim: "eduperson_entitlement"
    admin-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:admins#perun.bbmri-eric.eu"
    researcher-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu"
    biobanker-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory#perun.bbmri-eric.eu"
    subject-claim: "sub"
    resource-claim-prefix: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:"
notification:
  cron-schedule-expression: "0 */5 * ? * *"
logging:
  level:
    org.springframeworf.web: debug
    org.springframework.security: debug
    eu.bbmri_eric.negotiator: debug
