server:
  port: 8081
  servlet:
    context-path: "/api"
management:
  endpoint:
    health:
      enabled: true
      show-components: always
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
spring:
  mail:
    host: ""
    port: 0
    username: ""
    password: ""
  application:
    name: "Negotiator"
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: ""
          issuer-uri: ""
          jwks-url: ""
negotiator:
  frontend-url: ""
  authorization:
    claim: ""
    admin-claim-value: ""
    researcher-claim-value: ""
    biobanker-claim-value: ""
    subject-claim: ""
    resource-claim-prefix: ""
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

