-- Create state_machine table
CREATE TABLE state_machine
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_state_machine PRIMARY KEY (id)
);

ALTER TABLE state_machine
    ADD CONSTRAINT uc_state_machine_name UNIQUE (name);

-- Create state table
CREATE TABLE state
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state_machine_id BIGINT                                  NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    type             VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_state PRIMARY KEY (id)
);

ALTER TABLE state
    ADD CONSTRAINT fk_state_on_state_machine FOREIGN KEY (state_machine_id) REFERENCES state_machine (id);

ALTER TABLE state
    ADD CONSTRAINT uc_state_name_per_machine UNIQUE (state_machine_id, name);

-- Create transition table
CREATE TABLE transition
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source BIGINT                                  NOT NULL,
    target BIGINT                                  NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_transition PRIMARY KEY (id)
);

ALTER TABLE transition
    ADD CONSTRAINT fk_transition_on_source_state FOREIGN KEY (source) REFERENCES state (id);

ALTER TABLE transition
    ADD CONSTRAINT fk_transition_on_target_state FOREIGN KEY (target) REFERENCES state (id);

-- Add index for better performance when querying transitions by source
CREATE INDEX idx_transition_source ON transition (source);

-- Add index for better performance when querying transitions by target
CREATE INDEX idx_transition_target ON transition (target);

-- Add index for better performance when querying states by state_machine_id
CREATE INDEX idx_state_state_machine_id ON state (state_machine_id);

