alter table access_criteria add creation_date timestamp(6);
alter table access_criteria add modified_date timestamp(6);
alter table access_criteria add created_by bigint references person(id);
alter table access_criteria add modified_by bigint references person(id);

alter table access_criteria_section add creation_date timestamp(6);
alter table access_criteria_section add modified_date timestamp(6);
alter table access_criteria_section add created_by bigint references person(id);
alter table access_criteria_section add modified_by bigint references person(id);

alter table access_criteria_section_link add creation_date timestamp(6);
alter table access_criteria_section_link add modified_date timestamp(6);
alter table access_criteria_section_link add created_by bigint references person(id);
alter table access_criteria_section_link add modified_by bigint references person(id);

alter table access_criteria_set add creation_date timestamp(6);
alter table access_criteria_set add modified_date timestamp(6);
alter table access_criteria_set add created_by bigint references person(id);
alter table access_criteria_set add modified_by bigint references person(id);

alter table data_source add creation_date timestamp(6);
alter table data_source add modified_date timestamp(6);
alter table data_source add created_by bigint references person(id);
alter table data_source add modified_by bigint references person(id);

alter table negotiation_lifecycle_record rename column recorded_at to creation_date;

alter table negotiation_lifecycle_record add modified_date timestamp(6);
alter table negotiation_lifecycle_record add created_by bigint references person(id);
alter table negotiation_lifecycle_record add modified_by bigint references person(id);

alter table organization add creation_date timestamp(6);
alter table organization add modified_date timestamp(6);
alter table organization add created_by bigint references person(id);
alter table organization add modified_by bigint references person(id);

alter table post rename column request_id to negotiation_id;

create table negotiation_resource_lifecycle_record (
  id bigint generated by default as identity,
  created_by bigint references person(id),
  creation_date timestamp(6),
  modified_by bigint references person(id),
  modified_date timestamp(6),
  changed_to varchar(255) check (changed_to in ('SUBMITTED', 'REPRESENTATIVE_CONTACTED', 'REPRESENTATIVE_UNREACHABLE',
      'RETURNED_FOR_RESUBMISSION', 'CHECKING_AVAILABILITY', 'RESOURCE_AVAILABLE', 'RESOURCE_UNAVAILABLE_WILLING_TO_COLLECT',
      'RESOURCE_UNAVAILABLE', 'ACCESS_CONDITIONS_INDICATED', 'ACCESS_CONDITIONS_MET', 'RESOURCE_NOT_MADE_AVAILABLE',
      'RESOURCE_MADE_AVAILABLE'
  )),
  negotiation_id varchar(255) references negotiation(id),
  resource_id bigint references resource(id),
  primary key (id)
);
