ALTER TABLE ACCESS_CRITERIA_SECTION_LINK
    DROP CONSTRAINT CONSTRAINT_C06;

ALTER TABLE ACCESS_CRITERIA_SECTION_LINK
    DROP CONSTRAINT CONSTRAINT_C060;

ALTER TABLE ACCESS_CRITERIA_SECTION_LINK
    DROP CONSTRAINT FKCGJ2EXTN02C91Q2LD1XVP54DI;

ALTER TABLE ACCESS_CRITERIA_SECTION_LINK
    DROP CONSTRAINT FKHWQK0A4NXT3P18E97L4LLG4BS;

ALTER TABLE ACCESS_CRITERIA_SECTION
    DROP CONSTRAINT FKIJWHM9GJJ8QDO5EU09IIBXDBO;

CREATE SEQUENCE access_form_id_seq START WITH 100 INCREMENT BY 50;

CREATE SEQUENCE access_form_link_id_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE section_element_link_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE form_section_link
(
    id                         BIGINT NOT NULL,
    access_criteria_set_id     BIGINT,
    access_criteria_section_id BIGINT,
    CONSTRAINT pk_formsectionlink PRIMARY KEY (id)
);

CREATE TABLE section_element_link
(
    id                   BIGINT  NOT NULL,
    form_section_link_id BIGINT,
    access_criteria_id   BIGINT,
    is_required          BOOLEAN NOT NULL,
    CONSTRAINT pk_sectionelementlink PRIMARY KEY (id)
);

ALTER TABLE form_section_link
    ADD CONSTRAINT uc_formsectionlink_accrseidaccrseid UNIQUE (access_criteria_set_id, access_criteria_section_id);

ALTER TABLE form_section_link
    ADD CONSTRAINT FK_FORMSECTIONLINK_ON_ACCESS_CRITERIA_SECTION FOREIGN KEY (access_criteria_section_id) REFERENCES access_criteria_section (id);

ALTER TABLE form_section_link
    ADD CONSTRAINT FK_FORMSECTIONLINK_ON_ACCESS_CRITERIA_SET FOREIGN KEY (access_criteria_set_id) REFERENCES access_criteria_set (id);

ALTER TABLE section_element_link
    ADD CONSTRAINT FK_SECTIONELEMENTLINK_ON_ACCESS_CRITERIA FOREIGN KEY (access_criteria_id) REFERENCES access_criteria (id);

ALTER TABLE section_element_link
    ADD CONSTRAINT FK_SECTIONELEMENTLINK_ON_FORM_SECTION_LINK FOREIGN KEY (form_section_link_id) REFERENCES form_section_link (id);

DROP TABLE ACCESS_CRITERIA_SECTION_LINK CASCADE;

ALTER TABLE ACCESS_CRITERIA_SECTION
    DROP COLUMN ACCESS_CRITERIA_SET_ID;