ALTER TABLE ACCESS_CRITERIA
    DROP CONSTRAINT CONSTRAINT_8F;

ALTER TABLE ACCESS_CRITERIA
    DROP CONSTRAINT CONSTRAINT_8F4;

ALTER TABLE ACCESS_CRITERIA_SECTION
    DROP CONSTRAINT CONSTRAINT_DA;

ALTER TABLE ACCESS_CRITERIA_SECTION
    DROP CONSTRAINT CONSTRAINT_DAC;

ALTER TABLE ACCESS_CRITERIA_SET
    DROP CONSTRAINT CONSTRAINT_E8;

ALTER TABLE ACCESS_CRITERIA_SET
    DROP CONSTRAINT CONSTRAINT_E8C;

ALTER TABLE RESOURCE
    DROP CONSTRAINT FK1XA946OABSGLYYF25U09D0NUU;

ALTER TABLE ACCESS_CRITERIA
    DROP CONSTRAINT FKT4TRPXMXHENAXG0I4DUGGIOCR;

ALTER TABLE FORM_SECTION_LINK
    DROP CONSTRAINT FK_FORMSECTIONLINK_ON_ACCESS_CRITERIA_SECTION;

ALTER TABLE FORM_SECTION_LINK
    DROP CONSTRAINT FK_FORMSECTIONLINK_ON_ACCESS_CRITERIA_SET;

ALTER TABLE SECTION_ELEMENT_LINK
    DROP CONSTRAINT FK_SECTIONELEMENTLINK_ON_ACCESS_CRITERIA;

ALTER TABLE SECTION_ELEMENT_LINK
    DROP CONSTRAINT FK_SECTIONELEMENTLINK_ON_FORM_SECTION_LINK;

CREATE SEQUENCE access_form_section_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE access_form
(
    id            BIGINT NOT NULL,
    creation_date TIMESTAMP,
    modified_date TIMESTAMP,
    created_by    BIGINT,
    modified_by   BIGINT,
    name          VARCHAR(255),
    CONSTRAINT pk_accessform PRIMARY KEY (id)
);

CREATE TABLE access_form_element
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date          TIMESTAMP,
    modified_date          TIMESTAMP,
    created_by             BIGINT,
    modified_by            BIGINT,
    name                   VARCHAR(255)                            NOT NULL,
    label                  VARCHAR(255)                            NOT NULL,
    description            VARCHAR(255)                            NOT NULL,
    type                   VARCHAR(255)                            NOT NULL,
    access_form_section_id BIGINT,
    CONSTRAINT pk_accessformelement PRIMARY KEY (id)
);

CREATE TABLE access_form_section
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date TIMESTAMP,
    modified_date TIMESTAMP,
    created_by    BIGINT,
    modified_by   BIGINT,
    name          VARCHAR(255)                            NOT NULL,
    label         VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_accessformsection PRIMARY KEY (id)
);

CREATE TABLE access_form_section_element_link
(
    id                          BIGINT  NOT NULL,
    access_form_section_link_id BIGINT,
    access_form_element_id      BIGINT,
    is_required                 BOOLEAN NOT NULL,
    CONSTRAINT pk_accessformsectionelementlink PRIMARY KEY (id)
);

CREATE TABLE access_form_section_link
(
    id                     BIGINT NOT NULL,
    access_form_id         BIGINT,
    access_form_section_id BIGINT,
    CONSTRAINT pk_accessformsectionlink PRIMARY KEY (id)
);

ALTER TABLE access_form_section_link
    ADD CONSTRAINT uc_accessformsectionlink_acfoidacfoseid UNIQUE (access_form_id, access_form_section_id);

ALTER TABLE access_form_element
    ADD CONSTRAINT FK_ACCESSFORMELEMENT_ON_ACCESS_FORM_SECTION FOREIGN KEY (access_form_section_id) REFERENCES access_form_section (id);

ALTER TABLE access_form_element
    ADD CONSTRAINT FK_ACCESSFORMELEMENT_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES person (id);

ALTER TABLE access_form_element
    ADD CONSTRAINT FK_ACCESSFORMELEMENT_ON_MODIFIED_BY FOREIGN KEY (modified_by) REFERENCES person (id);

ALTER TABLE access_form_section_element_link
    ADD CONSTRAINT FK_ACCESSFORMSECTIONELEMENTLINK_ON_ACCESS_FORM_ELEMENT FOREIGN KEY (access_form_element_id) REFERENCES access_form_element (id);

ALTER TABLE access_form_section_element_link
    ADD CONSTRAINT FK_ACCESSFORMSECTIONELEMENTLINK_ON_ACCESS_FORM_SECTION_LINK FOREIGN KEY (access_form_section_link_id) REFERENCES access_form_section_link (id);

ALTER TABLE access_form_section_link
    ADD CONSTRAINT FK_ACCESSFORMSECTIONLINK_ON_ACCESS_FORM FOREIGN KEY (access_form_id) REFERENCES access_form (id);

ALTER TABLE access_form_section_link
    ADD CONSTRAINT FK_ACCESSFORMSECTIONLINK_ON_ACCESS_FORM_SECTION FOREIGN KEY (access_form_section_id) REFERENCES access_form_section (id);

ALTER TABLE access_form_section
    ADD CONSTRAINT FK_ACCESSFORMSECTION_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES person (id);

ALTER TABLE access_form_section
    ADD CONSTRAINT FK_ACCESSFORMSECTION_ON_MODIFIED_BY FOREIGN KEY (modified_by) REFERENCES person (id);

ALTER TABLE access_form
    ADD CONSTRAINT FK_ACCESSFORM_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES person (id);

ALTER TABLE access_form
    ADD CONSTRAINT FK_ACCESSFORM_ON_MODIFIED_BY FOREIGN KEY (modified_by) REFERENCES person (id);

ALTER TABLE RESOURCE
    ALTER COLUMN ACCESS_CRITERIA_SET_ID rename to ACCESS_FORM_ID;
ALTER TABLE resource
    ADD CONSTRAINT FK_RESOURCE_ON_ACCESS_FORM FOREIGN KEY (access_form_id) REFERENCES access_form (id);

DROP TABLE ACCESS_CRITERIA CASCADE;

DROP TABLE ACCESS_CRITERIA_SECTION CASCADE;

DROP TABLE ACCESS_CRITERIA_SET CASCADE;

DROP TABLE FORM_SECTION_LINK CASCADE;

DROP TABLE SECTION_ELEMENT_LINK CASCADE;

DROP SEQUENCE ACCESS_FORM_LINK_ID_SEQ;