package eu.bbmri.eric.csit.service.negotiator.configuration.state_machine.resource;

public enum NegotiationResourceState {
  SUBMITTED,
  REPRESENTATIVE_CONTACTED,
  REPRESENTATIVE_UNREACHABLE,
  RETURNED_FOR_RESUBMISSION,
  CHECKING_AVAILABILITY,
  RESOURCE_AVAILABLE,
  RESOURCE_UNAVAILABLE_WILLING_TO_COLLECT,
  RESOURCE_UNAVAILABLE,
  ACCESS_CONDITIONS_INDICATED,
  ACCESS_CONDITIONS_MET,
  RESOURCE_NOT_MADE_AVAILABLE,
  RESOURCE_MADE_AVAILABLE,
}
