const dateFormat = 'LL - LT'

const ROLES = {
  RESEARCHER: 'ROLE_RESEARCHER',
  REPRESENTATIVE: 'ROLE_REPRESENTATIVE',
  ADMINISTRATOR: 'ROLE_ADMIN',
}

const MESSAGE_STATUS = {
  SENT: 'CREATED',
  READ: 'READ',
}

const POST_TYPE = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
}

const NEGOTIATION_STATUS = {
  SUBMITTED: 'SUBMITTED',
  IN_PROGRESS: 'IN_PROGRESS',
  ABANDONED: 'ABANDONED',
}

const MAX_QUEUE_SIZE_NOTIFICATIONS = 3

const TIME_INTERVAL_NOTIFICATIONS = 3000

export { MESSAGE_STATUS, ROLES, POST_TYPE, NEGOTIATION_STATUS, dateFormat, MAX_QUEUE_SIZE_NOTIFICATIONS, TIME_INTERVAL_NOTIFICATIONS }
