INSERT INTO access_form_element (id, name, label, description, type)
VALUES (1, 'title', 'Title', 'Give a title', 'TEXT'),
       (2, 'description', 'Description', 'Give a description', 'TEXT_LARGE'),
       (3, 'description', 'Description', 'Provide a request description', 'TEXT_LARGE'),
       (4, 'ethics-vote', 'Ethics vote', 'Write the etchics vote', 'TEXT_LARGE'),
       (5, 'ethics-vote-attachment', 'Attachment', 'Upload Ethics Vote', 'FILE'),
       (6, 'objective', 'Study objective', 'Study objective or hypothesis to be tested?', 'TEXT'),
       (7, 'profit', 'Profit', 'Is it a profit or a non-profit study', 'BOOLEAN'),
       (8, 'acknowledgment', 'Acknowledgment', 'Financing/ Acknowledgement or collaboration of the collection PIs?',
        'TEXT'),
       (9, 'disease-code', 'Disease code', 'What is the Disease being studied (ICD 10 code) ?', 'TEXT'),
       (10, 'collection', 'Collection', 'Is the collection to be prospective or retrospective?', 'TEXT'),
       (11, 'donors', 'Donors', 'How many different subjects (donors) would you need?', 'NUMBER'),
       (12, 'samples', 'Samples', 'What type(s) of samples and how many samples per subject are needed?', 'TEXT'),
       (13, 'specifics', 'Specifics', 'Are there any specific requirements ( e.g. volume,… )?', 'TEXT'),
       (14, 'organization', 'Organization', 'What is the organization leading this project and where is it based',
        'TEXT')
ON CONFLICT(id) DO UPDATE SET type = EXCLUDED.type;
CREATE SEQUENCE IF NOT EXISTS value_set_id_seq START WITH 100 INCREMENT BY 50;

CREATE TABLE value_set
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255),
    external_documentation VARCHAR(255),
    CONSTRAINT pk_valueset PRIMARY KEY (id)
);

CREATE TABLE value_set_available_values
(
    value_set_id     BIGINT NOT NULL,
    available_values VARCHAR(255)
);
ALTER TABLE access_form_element
    add column value_set_id BIGINT;

ALTER TABLE access_form_element
    ADD CONSTRAINT FK_ACCESSFORMELEMENT_ON_LINKED_VALUE_SET FOREIGN KEY (value_set_id) REFERENCES value_set (id);

ALTER TABLE value_set_available_values
    ADD CONSTRAINT fk_valueset_availablevalues_on_value_set FOREIGN KEY (value_set_id) REFERENCES value_set (id);

ALTER TABLE access_form_element
    ALTER COLUMN creation_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE access_form_element
    ALTER COLUMN modified_date SET DEFAULT CURRENT_TIMESTAMP;
UPDATE access_form_element
SET modified_date = COALESCE(modified_date, CURRENT_TIMESTAMP),
    creation_date = COALESCE(creation_date, CURRENT_TIMESTAMP)
WHERE modified_date IS NULL
   OR creation_date IS NULL;
ALTER TABLE access_form_section
    ALTER COLUMN creation_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE access_form_section
    ALTER COLUMN modified_date SET DEFAULT CURRENT_TIMESTAMP;
UPDATE access_form_section
SET modified_date = COALESCE(modified_date, CURRENT_TIMESTAMP),
    creation_date = COALESCE(creation_date, CURRENT_TIMESTAMP)
WHERE modified_date IS NULL
   OR creation_date IS NULL;
ALTER TABLE access_form
    ALTER COLUMN creation_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE access_form
    ALTER COLUMN modified_date SET DEFAULT CURRENT_TIMESTAMP;
UPDATE access_form
SET modified_date = COALESCE(modified_date, CURRENT_TIMESTAMP),
    creation_date = COALESCE(creation_date, CURRENT_TIMESTAMP)
WHERE modified_date IS NULL
   OR creation_date IS NULL;