CREATE TABLE information_submission
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requirement_id BIGINT,
    resource_id    BIGINT,
    payload        JSONB,
    CONSTRAINT pk_informationsubmission PRIMARY KEY (id)
);

ALTER TABLE information_submission
    ADD CONSTRAINT FK_INFORMATIONSUBMISSION_ON_REQUIREMENT FOREIGN KEY (requirement_id) REFERENCES information_requirement (id);

ALTER TABLE information_submission
    ADD CONSTRAINT FK_INFORMATIONSUBMISSION_ON_RESOURCE FOREIGN KEY (resource_id) REFERENCES resource (id);