alter table public.access_criteria
    add column creation_date timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table public.access_criteria_section
    add column creation_date timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table public.access_criteria_section_link
    add column creation_date timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table public.access_criteria_set
    add column creation_date timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table public.data_source
    add column creation_date timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table public.negotiation_lifecycle_record rename column recorded_at to creation_date;

alter table public.negotiation_lifecycle_record
    alter column creation_date type timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table public.notification
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);


alter table public.organization
    add column creation_date timestamp(6) without time zone,
    add column modified_date timestamp(6) without time zone,
    add column created_by bigint references public.person(id),
    add column modified_by bigint references public.person(id);

alter table post rename column request_id to negotiation_id;

create table negotiation_resource_lifecycle_record (
  id bigint generated by default as identity,
  created_by bigint references person(id),
  creation_date timestamp(6),
  modified_by bigint references person(id),
  modified_date timestamp(6),
  changed_to varchar(255),
  negotiation_id varchar(255) references negotiation(id),
  resource_id bigint references resource(id),
  primary key (id),
  CONSTRAINT negotiation_resource_changed_to_check CHECK (((changed_to)::text = ANY ((ARRAY[
    'SUBMITTED'::character varying,
    'REPRESENTATIVE_CONTACTED'::character varying,
    'REPRESENTATIVE_UNREACHABLE'::character varying,
    'RETURNED_FOR_RESUBMISSION'::character varying,
    'CHECKING_AVAILABILITY'::character varying,
    'RESOURCE_AVAILABLE'::character varying,
    'RESOURCE_UNAVAILABLE_WILLING_TO_COLLECT'::character varying,
    'RESOURCE_UNAVAILABLE'::character varying,
    'ACCESS_CONDITIONS_INDICATED'::character varying,
    'ACCESS_CONDITIONS_MET'::character varying,
    'RESOURCE_NOT_MADE_AVAILABLE'::character varying,
    'RESOURCE_MADE_AVAILABLE'::character varying
  ])::text[])))
);
