CREATE SEQUENCE IF NOT EXISTS value_set_id_seq START WITH 100 INCREMENT BY 50;

CREATE TABLE value_set
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255),
    external_documentation VARCHAR(255),
    CONSTRAINT pk_valueset PRIMARY KEY (id)
);

CREATE TABLE value_set_available_values
(
    value_set_id     BIGINT NOT NULL,
    available_values VARCHAR(255)
);
ALTER TABLE access_form_element
    add column value_set_id BIGINT;

ALTER TABLE access_form_element
    ADD CONSTRAINT FK_ACCESSFORMELEMENT_ON_LINKED_VALUE_SET FOREIGN KEY (value_set_id) REFERENCES value_set (id);

ALTER TABLE value_set_available_values
    ADD CONSTRAINT fk_valueset_availablevalues_on_value_set FOREIGN KEY (value_set_id) REFERENCES value_set (id);