swagger: "2.0"
info:
  description: >-
    BBMRI-ERIC Negotiator Service API. The Service is running at
    [https://negotiator.bbmri-eric.eu](https://negotiator.bbmri-eric.eu)
  version: 1.0.0
  title: BBMRI-ERIC Negotiator
  termsOfService: 'https://bbmri-eric.eu'
  contact:
    email: robert.reihs@bbmri-eric.eu
  license:
    name: '?????'
    url: 'https://bbmri-eric.eu'
host: negotiator.bbmri-eric.eu
basePath: /api
schemes:
  - https
  
tags:
  - name: status
    description: Deployed BBMRI-ERIC Negotiator Version and Statistics.
  - name: directory
    description: Access to Petstore orders
  - name: list
    description: List of Biobanks and Collections in all directories

paths:
  /status:
    get:
      tags:
        - status
      summary: Get overview
      description: >-
        Listes depoyed version of the BBMRI-ERIC Negotiator service, basic
        statistic of the service.
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Status'
        '400':
          description: Invalid status value
  /directory/create_query:
    post:
      tags:
        - directory
      summary: Creates a new query.
      description: >-
        Takes a JSON query object with information of the search criteria and
        results of the directory. Stores it temporary in the database and
        returns a redirect URL for the directory. With this URL the directory
        can redirect the user to the query edit page. I case of updating a
        existing query or extending an exiting request, a token is provided for
        identification.
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Query parameters"
        required: true
        schema:
          $ref: '#/definitions/Query'
      responses:
        '201':
          description: successful created
          schema:
            $ref: '#/definitions/QueryCreateResponse'
  /v2/list:
    get:
      tags:
        - list
      summary: List of Biobanks and Collections in all directories
      description: >-
        Returns a JSON array with a hierarchical structure of all directories integrated into the \Negotiator. For each directory all biobanks registered are listed with the identifying ID of the directory. In the biobank a list of all associated collections is listed.
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/List'
    
definitions:
  Status:
    type: object
    properties:
      biobanks:
        type: integer
        format: int64
      attachments:
        type: integer
        format: int64
      collections:
        type: integer
        format: int64
      queries_with_matches:
        type: integer
        format: int64
      build_time:
        type: string
        pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$'
      used:
        type: integer
        format: int64
      free:
        type: integer
        format: int64
      queries:
        type: integer
        format: int64
      version:
        type: string
      users:
        type: integer
        format: int64
  Query:
    type: object
    properties:
      URL:
        type: string
      humanReadable:
        type: string
      collections:
        type: array
        items:
          type: object
          properties:
            biobankId:
              type: integer
              format: int64
            collectionId:
              type: integer
              format: int64
  QueryCreateResponse:
    type: object
    properties:
      redirect_uri:
        type: string
  List:
    type: array
    items:
      type: object
      properties:
        directory:
          type: object
          properties:
            name:
              type: string
            url:
              type: string
            description:
              type: string
            Biobanks:
              type: array
              items:
                type: object
                properties:
                  directory_id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  collections:
                    type: array
                    items:
                      type: object
                      properties:
                        directory_id:
                          type: integer
                          format: int64
                        name:
                          type: string