spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/negotiator
    username: negotiator
    password: negotiator
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  sql:
    init:
      mode: never
  jackson:
    date-format: "yyyy-MM-dd"
  flyway:
    locations: classpath:db/migration/,filesystem:/app/data
logging:
  file:
    name: "/var/log/negotiator/negotiator.log"
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    org.springframeworf.web: info
    org.springframework.security: info
    eu.bbmri_eric.negotiator: info
negotiator:
  emailLogo: "https://web.bbmri-eric.eu/Negotiator/2023-BBMRI-ERIC-Logo_NEGOTIATOR.png"