server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081
  servlet:
    context-path: "/api"
management:
  metrics:
    tags:
      application: Negotiator
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-components: always
    prometheus:
      ip: "::1"
  info:
    env:
      enabled: true
    build:
      enabled: true
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
spring:
  mail:
    host: "localhost"
    port: 1025
    username: "user"
    password: "pass"
    properties:
      debug: false
      starttls: true
      auth: true
    protocol: "smtp"
  application:
    name: "Negotiator"
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "*"
      allow-credentials: false
      max-age: 3600
    csrf:
      enabled: false
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ""
          client-secret: ""
          introspection-uri: ""
        jwt:
          user-info-uri: ""
          issuer-uri: ""
          jwks-url: ""
          type: "JWT"
          audiences: "https://negotiator.bbmri-eric.eu,negotiator-api"
  profiles:
    default: prod
negotiator:
  frontend-url: ""
  emailYoursSincerelyText: "The BBMRI-ERIC Team"
  emailHelpdeskHref: "mailto:negotiator@helpdesk.bbmri-eric.eu"
  emailLogo: "http://localhost:8081/api/images/negotiator_logo.png"
  pdfFont: "/fonts/OpenSans.ttf"
  authorization:
    claim: "eduperson_entitlement"
    admin-claim-value: ""
    researcher-claim-value: ""
    biobanker-claim-value: ""
  notification:
    reminder-cron-expression: "0 0 6 * * *"
  email:
    frequency-cron-expression: "0 0 * * * *"
logging:
  pattern:
    level: "%p"
  level:
    root: info
springdoc:
  show-actuator: true
  oAuthFlow:
    authorizationUrl: ""
    tokenUrl: ""
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ""
      client-secret: ""
      scopes: ""
    tags-sorter: "alpha"
    operations-sorter: "alpha"
info:
  application:
    name: "BBMRI-ERIC Negotiator"
    description: "An Open-source access negotiation system for Research Infrastructures."
    environment: "Production"
    license:
      name: "GNU Affero General Public License v3.0"
      url: "https://www.gnu.org/licenses/agpl-3.0.en.html#license-text"
synchronization:
  frequency: "0 0 0 * * ?"
  discoveryServiceId: "1"
