spring:
  flyway:
    clean-disabled: false
    locations: classpath:db/migration/, classpath:db/test/migration
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://testoidc"
          type: "JWT"
  thymeleaf:
    prefix: "file:../config/templates/"
negotiator:
  frontend-url: "http://localhost"
  authorization:
    claim: "authz"
    admin-claim-value: "admin_group"