server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: '%{yyyy-MM-dd HH:mm:ss.SSS}t DEBUG [%m] %h %l %u %t "%r" %s'
spring:
  mail:
    host: "localhost"
    port: 1025
    username: "user"
    password: "pass"
  # enable remote debugging:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:tc:postgres:///negotiator
    username: negotiator
    password: negotiator
    database: negotiator
  flyway:
    locations: classpath:db/migration/,db/dev/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          user-info-uri: "http://localhost:4011/connect/userinfo"
          issuer-uri: "http://localhost:4011"
          jwk-set-uri: "http://localhost:4011/.well-known/openid-configuration/jwks"
        opaquetoken:
          client-id: "https%3A//negotiator.bbmri-eric.eu"
          client-secret: "negotiator-secret"
          introspection-uri: "http://localhost:4011/connect/introspect"
  thymeleaf:
    cache: false
    prefix: "file:./config/templates/"
springdoc:
  oAuthFlow:
    authorizationUrl: "http://localhost:4011/connect/authorize"
    tokenUrl: "http://localhost:4011/connect/token"
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: "auth-code-client"
      scopes: "openid profile email permissions some-app-scope-1"
      app-name: "Swagger UI"
      additional-query-string-params:
        {
          "resource": "https://negotiator.bbmri-eric.eu"
        }
negotiator:
  frontend-url: "http://localhost:8080"
  authorization:
    admin-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:admins#perun.bbmri-eric.eu"
    researcher-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu"
    biobanker-claim-value: "urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory#perun.bbmri-eric.eu"
  notification:
    reminder-cron-expression: "0 */2 * * * *"
  email:
    frequency-cron-expression: "0 */1 * * * *"
logging:
  level:
    org:
      springframework:
        security: debug
        jdbc:
          datasource:
            init:
              ScriptUtils: debug
    org.springframeworf.web: debug
    eu.bbmri_eric.negotiator: debug