server:
  port: 8080
spring:
  application:
    name: "Negotiator"
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    open-in-view: false
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

