spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:negotiator;INIT=RUNSCRIPT FROM 'classpath:dev/init.sql'
    username: negotiator
    password: negotiator
    initialize: true
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

negotiator:
  authorization:
    claim: "authz"
    adminClaimValue: "admin_group"
    researcherClaimValue: "researcher_group"
    biobankerClaimValue: "biobanker_group"
    subjectClaim: "subject_id"
