spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      show-sql: false
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: ${DB_HIBERNATE_DIALECT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER}

