name: SonarQube
env:
  JAVA_VERSION: '21'
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  check-sonar-token:
    name: Check SonarQube token
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      has-sonarqube-token: ${{ steps.check-token.outputs.has-sonarqube-token }}
    steps:
      - name: Check SonarQube token
        id: check-token
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -n "$SONAR_TOKEN" ]; then
            echo "has-sonarqube-token=true" >> "$GITHUB_OUTPUT"
            echo "SONAR_TOKEN secret is set."
          else
            echo "has-sonarqube-token=false" >> "$GITHUB_OUTPUT"
            echo "SONAR_TOKEN secret is not set."
          fi

  build:
    name: Build and analyze
    needs: check-sonar-token
    if: ${{ needs.check-sonar-token.outputs.has-sonarqube-token == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          cache: maven
          
      - name: Cache SonarQube packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Scan Backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -f backend/pom.xml clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BBMRI-ERIC_negotiator -DskipTests=true

      - name: Scan Frontend
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        with:
          projectBaseDir: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}